# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Pigeon Super Model
author: Guillermo Hidalgo Gadea & Sarah C. Möser, IKN, Ruhr-University Bochum
copyright: "2022"
email: guillermo.hidalgogadea@rub.de
logo: Figures/PigeonSuperModel.jpg

# Auto-exclude files not in the toc
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "off"

# Information about where the book exists on the web
repository:
  url: https://gitlab.ruhr-uni-bochum.de/ikn/pigeonsupermodel  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: icon.ico
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: true
